version: '3'
services:
  db:
    image: postgres:9.6.2
    ports:
      - "5432:5432"
  web:
    build: .
    command: foreman start -f Procfile.dev
    ports:
      - "3000:3000"
    links:
      - db
      - appeals-redis
    volumes:
      - .:/caseflow
  appeals-redis:
    image: redis:2.8.23
    ports:
      - "6379:6379"